[package]
name = "irox-mbtiles"
description = ""
keywords = ["irox"]
categories = []
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
rusqlite.workspace = true
irox-units.workspace = true
