version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "spmadden"
    assignees:
      - "spmadden"
    commit-message:
      prefix: "feat"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "spmadden"
    assignees:
      - "spmadden"
    commit-message:
      prefix: "feat"
      include: "scope"