[package]
name = "irox-types"
description = "Enums and structs to describe Rust's basic type system"
keywords = ["irox", "reflection", "types", "primitives"]
categories = ["rust-patterns", "development-tools"]
version= "0.4.3"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
syn = ["dep:syn"]
bits = ["dep:irox-bits"]

[dependencies]
irox-enums.workspace = true
irox-enums_derive.workspace = true
irox-tools.workspace = true
irox-bits = {workspace = true, optional = true}
syn = {workspace = true, optional = true}
