accepted = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "BSL-1.0",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Zlib",
    "OpenSSL",
    "Unicode-3.0",
    "MPL-2.0",
    "NOASSERTION",
    "CC0-1.0",
    "CDLA-Permissive-2.0"
]
no-clearly-defined = true
workarounds = ["ring", "unicode-ident"]

[epaint_default_fonts.clarify]
license = "(MIT OR Apache-2.0) AND OFL-1.1 AND Ubuntu-font-1.0"
[[epaint_default_fonts.clarify.files]]
path = "fonts/UFL.txt"
license = "Ubuntu-font-1.0"
checksum = "2f0015108d68627bd788d313f529c21ff4da2c2c42a5e1f3883acc83480f9002"