[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Sean P. Madden <sean@seanmadden.net>"]
homepage = "https://github.com/spmadden/irox"
license = "MIT OR Apache-2.0"
exclude = ["doc"]
readme = "README.md"
repository = "https://github.com/spmadden/irox"

[workspace]
resolver = "2"
members = [
    "irox",
    "data-formats/csv",
    "data-formats/gpx",
    "data-formats/nmea0183",
    "data-formats/raymarine-sonar",
    "data-formats/sirf",
    "interfaces/influxdb_v1",
    "interfaces/win-location-api",
    "libraries/carto",
    "libraries/egui_extras",
    "libraries/enums",
    "libraries/enums_derive",
    "libraries/network",
    "libraries/stats",
    "libraries/units",
    "libraries/structs",
    "libraries/structs_derive",
    "libraries/time",
    "libraries/tools",
    "libraries/types",
    "tools/halflifes",
    "tools/gpsd"
]

[workspace.dependencies]
egui = { version = "=0.23.0", features = ["persistence"] }
eframe = { version = "=0.23.0", features = ["persistence"] }
egui_plot = { version = "=0.23.0", features = [] }
ron = { version = "=0.8.1", features = ["integer128"] }
serde = { version = "=1.0.188", features = ["derive"] }
serde_json = {version = "=1.0.107", features = []}
time = {version = "=0.3.29", features = ["formatting", "macros"]}
ureq = {version = "=2.8.0", features = ["brotli", "native-certs", "socks-proxy", "cookies"]}
url = {version = "=2.4.1", features = []}
clap = {version = "=4.4.6", features = ["derive", "wrap_help", "string", "cargo", "env"]}
clap-verbosity-flag = {version = "=2.0.1"}
log = {version = "=0.4.20", features = []}
env_logger = {version = "=0.10.0", features = []}
syn = {version = "=2.0.38", features = ["extra-traits"]}
quote = {version = "=1.0.33", features = []}
signal-hook = {version = "=0.3.17", features = []}
futures = {version = "=0.3.28", features = []}
windows = {version = "=0.51.1", features = [ "Devices_Geolocation", "Foundation" ]}
rusqlite = {version = "=0.29.0", features = ["bundled", "bundled-windows"]}
miniz_oxide = {version = "=0.7.1", features = []}
xml = {version = "=0.8.10", features = []}
serial = {version = "=0.4.0", features = []}
human-panic = {version = "=1.2.1", features = []}
proc-macro2 = {version = "=1.0.69", features = []}

irox-csv = {path = "data-formats/csv"}
irox-gpx = {path = "data-formats/gpx"}
irox-nmea0183 = {path = "data-formats/nmea0183"}
irox-raymarine-sonar = {path = "data-formats/raymarine-sonar"}
irox-sirf = {path = "data-formats/sirf"}

irox-influxdb_v1 = {path = "interfaces/influxdb_v1"}
irox-winlocation-api = {path = "interfaces/win-location-api"}

irox-carto = {path = "libraries/carto"}
irox-egui-extras = {path = "libraries/egui_extras"}
irox-enums = {path = "libraries/enums"}
irox-enums_derive = {path = "libraries/enums_derive"}
irox-networking = {path = "libraries/network"}
irox-stats = {path = "libraries/stats"}
irox-structs = {path = "libraries/structs"}
irox-structs_derive = {path = "libraries/structs_derive"}
irox-time = {path = "libraries/time"}
irox-tools = {path = "libraries/tools"}
irox-types = {path = "libraries/types"}
irox-units = {path = "libraries/units"}
