[package]
name = "irox-egui-extras"
description = "Extras & tweaks for the egui framework"
keywords = ["irox", "egui", "gui"]
categories = ["gui"]
version = "0.5.4"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme = "README.md"
repository.workspace = true

[lints]
workspace = true

[features]
default = []
serde = ["dep:serde", "egui/serde", "dep:irox-tools", "dep:irox-bits"]
plots = ["dep:irox-tools"]
profiling = ["dep:puffin", "egui/puffin"]

[dependencies]
egui.workspace = true
eframe = { workspace = true, features = ["x11", "wayland"] }
ron.workspace = true
serde = { workspace = true, optional = true }
irox-bits = { workspace = true, optional = true, features = ["alloc"] }
irox-tools = { workspace = true, optional = true }
irox-imagery = { workspace = true }
irox-stats = { workspace = true, features = ["emath"] }
log.workspace = true
puffin = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
eframe = { workspace = true, features = ["wgpu"] }
wasm-bindgen-futures.workspace = true

[dev-dependencies]
eframe = { workspace = true, features = ["default"] }

[[example]]
name = "irox_egui_gallery"
required-features = ["serde", "plots"]

[build-dependencies]
irox-build-rs.workspace = true
