[package]
name = "irox-egui-extras"
description = "Extras & tweaks for the egui framework"
keywords = ["irox", "egui", "gui"]
categories = ["gui"]
version= "0.3.8"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme = "README.md"
repository.workspace = true

[lints]
workspace = true

[features]
default = []
serde = ["dep:serde", "egui/serde", "dep:irox-tools"]

[dependencies]
egui.workspace = true
eframe = {workspace = true, features=["x11", "wayland"]}
ron.workspace = true
serde = {workspace = true, optional = true }
irox-tools = {workspace = true, optional = true}
log.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
eframe = {workspace = true, features = ["glow"]}
wasm-bindgen-futures.workspace = true

[dev-dependencies]
eframe = {workspace = true, features = ["default"]}

[[example]]
name = "irox_egui_gallery"
required-features = ["serde"]

