[package]
name = "irox-egui-extras"
description = "Extras & tweaks for the egui framework"
keywords = ["irox", "egui", "gui"]
categories = ["gui"]
version= "0.3.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme = "README.md"
repository.workspace = true

[dependencies]
egui.workspace = true
eframe.workspace = true
ron.workspace = true
