[package]
name = "irox-egui-extras"
description = "Extras & tweaks for the egui framework"
keywords = ["irox", "egui", "gui"]
categories = ["gui"]
version = "0.5.5"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme = "README.md"
repository.workspace = true

[lints]
workspace = true

[features]
default = []
serde = ["dep:serde", "egui/serde", "dep:irox-tools", "dep:irox-bits"]
plots = ["dep:irox-tools", "dep:irox-units"]
profiling = ["dep:profiling", "dep:puffin"]
dump_csv = []

[dependencies]
egui.workspace = true
eframe = { workspace = true, features = [] }
ron.workspace = true
serde = { workspace = true, optional = true }
irox-bits = { workspace = true, optional = true, features = ["alloc"] }
irox-tools = { workspace = true, optional = true, features = ["std"] }
irox-time = { workspace = true, features = ["std"] }
irox-units = { workspace = true, optional = true, features = ["std"] }
irox-imagery = { workspace = true }
irox-stats = { workspace = true, features = ["emath", "std"] }
log.workspace = true
profiling = { workspace = true, optional = true }
puffin = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
eframe = { workspace = true, features = ["wgpu"] }
wasm-bindgen-futures.workspace = true

[dev-dependencies]
eframe = { workspace = true, features = ["glow", "default_fonts"] }
egui = { workspace = true, features = ["rayon"] }
irox-time = { workspace = true, features = ["std"] }
irox-tools = { workspace = true, features = ["std"] }
puffin_http = { workspace = true }
irox-csv = { workspace = true }

[target.'cfg(target_os = "linux")'.dev-dependencies]
eframe = { workspace = true, features = ["x11", "wayland"] }

[[example]]
name = "irox_egui_gallery"
required-features = ["serde", "plots"]

[[example]]
name = "plotsperf"
required-features = ["plots"]

[build-dependencies]
irox-build-rs.workspace = true
