[package]
name = "irox-influx-cli"
description = "Command line test tool to interface with the InfluxDB V1 API"
keywords = ["irox"]
categories = ["command-line-utilities", "database"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
irox-influxdb_v1.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true

