[package]
name = "irox-time"
description = "Date and Time types to manage the inherent complexity of dealing with the fourth dimension."
keywords = ["irox", "date", "time", "iso8601"]
categories = ["date-and-time", "encoding", "parser-implementations", "science", "value-formatting"]
version= "0.3.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
irox-units.workspace = true
irox-tools.workspace = true
irox-enums.workspace = true
