[package]
name = "irox-halflifes"
description = "GUI Tool to calculate the halflives of things"
keywords = ["irox", "gui", "tool"]
categories = ["science", "visualization"]
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
profiling = []

[dependencies]
eframe = { workspace = true, default-features = false, features = ["default_fonts"] }
egui = { workspace = true, default-features = false, features = ["persistence"] }
log.workspace = true
irox-egui-extras = { workspace = true, features = ["serde", "plots"] }
irox-stats.workspace = true
puffin_http = { workspace = true }
puffin = { workspace = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
eframe = { workspace = true, default-features = false, features = ["wgpu", "x11", "wayland"] }

[target.'cfg(target_arch="wasm32")'.dependencies]
eframe = { workspace = true, features = ["wgpu"] }
wasm-bindgen-futures.workspace = true

