[package]
name = "irox-halflifes"
description = "GUI Tool to calculate the halflives of things"
keywords = ["irox", "gui", "tool"]
categories = ["science", "visualization"]
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
eframe = {workspace = true, features = ["glow", "default_fonts"]}
egui = {workspace = true, features = ["persistence"]}
egui_plot.workspace = true
log.workspace = true
irox-egui-extras = {workspace = true, features = ["serde"]}
irox-stats.workspace = true

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen-futures.workspace = true
