[package]
name = "halflifes"
description = "GUI Tool to calculate the halflives of things"
keywords = ["irox", "gui", "tool"]
categories = ["science", "visualization"]
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
eframe.workspace = true
egui.workspace = true
ron.workspace = true
serde.workspace = true
irox-egui-extras = {version = "^0", path = "../../libraries/egui_extras" }
irox-stats = {version = "^0", path = "../../libraries/stats"}