[package]
name = "irox-halflifes"
description = "GUI Tool to calculate the halflives of things"
keywords = ["irox", "gui", "tool"]
categories = ["science", "visualization"]
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
eframe.workspace = true
egui.workspace = true
egui_plot.workspace = true
log.workspace = true
irox-egui-extras.workspace = true
irox-stats.workspace = true
