[package]
name = "irox-threading"
description = "Blocking and Asynchronous Threading Tools"
keywords = ["irox", "asynchronous", "concurrency", "threads", "parallel-processing"]
categories = ["asynchronous", "concurrency", "rust-patterns"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = []

[dependencies]
log = "0.4.20"
irox-log = {workspace = true}
num_cpus = {workspace = true, optional = true}
