[package]
name = "irox-fixedmath"
description = "Fixed Precision Math Primitives"
keywords = ["irox"]
categories = ["embedded", "mathematics", "no-std"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]

[dev-dependencies]
irox-tools.workspace = true