[package]
name = "irox-units"
description = "Physical Quantities, Units, & Reference Frames Library"
keywords = ["irox", "coordinate", "transforms", "epsg", "projections"]
categories = ["aerospace", "data-structures", "science", "mathematics"]
version= "0.3.3"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
