[package]
name = "irox-units"
description = "Physical Quantities, Units, & Reference Frames Library"
keywords = ["irox", "coordinate", "epsg", "projections", "no_std", "no_alloc"]
categories = ["aerospace", "data-structures", "science", "mathematics", "no-std::no-alloc"]
version= "0.3.4"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
irox-tools = {version = "^0", path = "../tools", default-features = false}

[features]
default = []
std_errors = []