[package]
name = "irox-progress"
description = "An ecosystem for displaying progress, either in a UI or on the terminal."
keywords = ["irox", "progress", "egui", "cli"]
categories = ["command-line-interface", "concurrency", "gui"]
version= "0.1.1"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = []
egui = ["dep:egui", "dep:eframe", "dep:irox-egui-extras"]

[dependencies]
irox-time.workspace = true
irox-tools.workspace = true
log.workspace = true
egui = {workspace = true, optional = true}
eframe = {workspace= true, optional = true}
irox-egui-extras = {workspace = true, optional = true}

[[example]]
name = "egui-progress"
required-features = ["egui"]
