[package]
name = "irox-progress"
description = "An ecosystem for displaying progress, either in a UI or on the terminal."
keywords = ["irox", "progress", "cli"]
categories = ["command-line-interface", "concurrency", "gui"]
version = "0.5.2"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[features]
default = []

[dependencies]
irox-time = { workspace = true, features = ["std"] }
irox-tools = {workspace = true, features = ["std"]}
irox-bits.workspace = true
log.workspace = true

