[package]
name = "irox-winlocation-api"
description = "Rust ergonomic adapter for the Windows Devices Location API"
keywords = ["windows", "api-bindings", "gps", "location", "geospatial"]
categories = ["api-bindings", "science::geo", "aerospace::protocols"]
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true

[dependencies]
windows.workspace = true

time.workspace = true
log.workspace = true
futures.workspace = true
irox-carto.workspace = true
irox-units.workspace = true