[package]
name = "irox-compression"
description = "Compression Algorithms"
keywords = ["irox", "compression", "no-std"]
categories = ["algorithms", "compression", "no-std"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dev-dependencies]
irox-bits = {workspace = true, features = ["std"]}
irox-tools = {workspace = true, features = ["std"]}

[dependencies]
irox-bits.workspace = true
irox-tools.workspace = true
