[package]
name = "irox-imagery"
description = "Image processing, manipulation, formats"
keywords = ["irox", "imagery"]
categories = ["graphics", "encoding", "parsing"]
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
irox-log = { workspace = true }
irox-bits = { workspace = true, features = ["std"] }
irox-tools = { workspace = true, features = ["std"] }
irox-units.workspace = true
irox-carto.workspace = true
irox-types.workspace = true