[package]
name = "irox"
description = "irox Rust Tools & Libraries"
keywords = ["irox"]
categories = ["aerospace", "science", "mathematics"]
version= "0.2.1"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = []
csv = ["irox-csv"]
gpx = ["irox-gpx"]
nmea0183 = ["irox-nmea0183"]
raymarine-sonar = ["irox-raymarine-sonar"]
sirf = ["irox-sirf"]
influxdb_v1 = ["irox-influxdb_v1"]
win-loc-api = ["irox-winlocation-api"]
carto = ["irox-carto"]
egui-extras = ["irox-egui-extras"]
enums = ["irox-enums"]
enums_derive = ["irox-enums_derive"]
networking = ["irox-networking"]
stats = ["irox-stats"]
structs = ["irox-structs"]
structs_derive = ["irox-structs_derive"]
time = ["irox-time"]
tools = ["irox-tools"]
types = ["irox-types"]
units = ["irox-units"]

[dependencies]
irox-csv = { version = "0.2.1", optional = true, path = "../data-formats/csv"}
irox-gpx = { version = "0.1.0", optional = true, path = "../data-formats/gpx"}
irox-nmea0183 = { version = "0.1.0", optional = true, path = "../data-formats/nmea0183"}
irox-raymarine-sonar = { version = "0.1.0", optional = true, path = "../data-formats/raymarine-sonar"}
irox-sirf = { version = "0.2.0", optional = true, path = "../data-formats/sirf"}

irox-influxdb_v1 = { version = "0.2.0", optional = true, path = "../interfaces/influxdb_v1"}
irox-winlocation-api = {version = "0.1.1", optional = true, path = "../interfaces/win-location-api"}

irox-carto = { version = "0.2.1", optional = true, path = "../libraries/carto"}
irox-egui-extras = { version = "0.2.1", optional = true, path = "../libraries/egui_extras"}
irox-enums = { version = "0.2.0", optional = true, path = "../libraries/enums"}
irox-enums_derive = { version = "0.2.0", optional = true, path = "../libraries/enums_derive"}
irox-networking = { version = "0.2.1", optional = true, path = "../libraries/network"}
irox-stats = { version = "0.2.1", optional = true, path = "../libraries/stats"}
irox-structs = { version = "0.2.0", optional = true, path = "../libraries/structs"}
irox-structs_derive = { version = "0.2.1", optional = true, path = "../libraries/structs_derive"}
irox-time = { version = "0.1.0", optional = true, path = "../libraries/time"}
irox-tools = { version = "^0.2.2", optional = true, path = "../libraries/tools"}
irox-types = { version = "0.2.1", optional = true, path = "../libraries/types"}
irox-units = { version = "0.2.0", optional = true, path = "../libraries/units"}
