[package]
name = "irox"
description = "irox Rust Tools & Libraries"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = []
csv = ["irox-csv"]
nmea0183 = ["irox-nmea0183"]
sirf = ["irox-sirf"]
influxdb_v1 = ["irox-influxdb_v1"]
win-loc-api = ["irox-winlocation-api"]
carto = ["irox-carto"]
egui-extras = ["irox-egui-extras"]
networking = ["irox-networking"]
stats = ["irox-stats"]
tools = ["irox-tools"]
units = ["irox-units"]

[dependencies]
irox-csv = { workspace = true, optional = true}
irox-nmea0183 = { workspace = true, optional = true}
irox-sirf = { workspace = true, optional = true}

irox-influxdb_v1 = { workspace = true, optional = true}
irox-winlocation-api = {workspace = true, optional = true}

irox-carto = { workspace = true, optional = true}
irox-egui-extras = { workspace = true, optional = true}
irox-networking = { workspace = true, optional = true}
irox-stats = { workspace = true, optional = true}
irox-tools = { workspace = true, optional = true}
irox-units = { workspace = true, optional = true}
