[package]
name = "irox-metrics"
description = "Secure metrology for your application & library"
keywords = ["irox"]
categories = ["config", "data-structures", "development-tools::debugging", "network-programming"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[features]

[lints]
workspace = true

[dependencies]
irox-bits.workspace = true
irox-time.workspace = true
irox-types = { workspace = true, features = ["bits"] }
irox-tools = {workspace = true, features = ["std"]}

x25519-dalek = { version ="2", features = ["getrandom", "static_secrets"] }
ed25519-dalek = { version = "2", features = [] }
crypto_box = {version = "0", features = ["chacha20", "seal"]}
crypto_secretbox = {version = "0", features = ["chacha20"]}
blake2 = {version = "0"}
p384 = {version = "0", features = []}
spki = {version = "0"}

[dev-dependencies]
criterion.workspace = true

[lib]
bench = false

[[bench]]
name = "metrics_bench"
harness = false