[package]
name = "irox-metrics"
description = "Secure metrology for your application & library"
keywords = ["irox"]
categories = ["config", "data-structures", "development-tools::debugging", "network-programming"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = ["std"]
std = []

[lints]
workspace = true

[dependencies]
irox-bits.workspace = true
irox-time = { workspace = true, features = ["std"] }
irox-types = { workspace = true, features = ["bits"] }
irox-tools = {workspace = true, features = ["std"]}
irox-cryptids = {workspace = true, features = ["std"]}

[dev-dependencies]
criterion.workspace = true

[lib]
bench = false

[[bench]]
name = "metrics_bench"
harness = false
