@startdot

digraph DEPS {
        irox_tools -> irox_bits
        irox_units -> irox_tools
        irox_fixedmath -> irox_tools

        irox_time -> {
            irox_enums
            irox_units
            irox_tools
            irox_fixedmath
        }

        irox_carto -> {
            irox_tools
            irox_enums
            irox_time
        }
        irox_carto -> irox_units;

        irox_cryptids -> {irox_bits irox_tools}

        irox_types -> {
            irox_enums
            irox_tools
        }
        irox_types -> irox_bits [style=dashed,label="feature[bits]"];

        irox_imagery -> {
            irox_log
            irox_bits
            irox_tools
            irox_units
            irox_carto
            irox_types
        }
        irox_stats -> {
            irox_tools
            irox_bits
            irox_types
            irox_time
            irox_units
        }

        irox_progress -> {
            irox_tools [label="feature[std]"]
            irox_bits [label="feature[std]"]
            irox_time [label="feature[std]"]
            log
        }

        irox_structs -> irox_bits

        irox_build_rs -> irox_time [label="feature[std]"]

        irox_csv -> irox_tools

        irox_dot -> irox_bits

        irox_log -> {log irox_tools}
        irox_log -> irox_time [label="feature[std]"]

        log [shape=component]

        irox_compression -> irox_bits
        irox_compression -> irox_tools

        !procedure $module($name, $std, $alloc)
            !if ($std == "required")
                $name [label=<
                   <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="2" STYLE="ROUNDED">
                       <TR><TD COLSPAN="2"><B>$name</B></TD></TR>
                       <TR>
                           <TD BGCOLOR="#555555" WIDTH="22" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> std</FONT></TD>
                           <TD BGCOLOR="#9f9f9f" WIDTH="50" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">required</FONT></TD>
                       </TR>
                       </TABLE>>]
            !elseif ($std == "feature") && ($alloc == "required")
                $name [label=<
                  <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="2" STYLE="ROUNDED">
                  <TR><TD COLSPAN="2"><B>$name</B></TD></TR>
                  <TR>
                     <TD BGCOLOR="#555555" WIDTH="30" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> std</FONT></TD>
                     <TD BGCOLOR="#007ec6" WIDTH="41" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">feature</FONT></TD>
                 </TR>
                  <TR>
                        <TD BGCOLOR="#555555" WIDTH="31" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> alloc</FONT></TD>
                       <TD BGCOLOR="#9f9f9f" WIDTH="50" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">required</FONT></TD>
                    </TR>
                  </TABLE>>]
            !elseif ($std == "feature") && ($alloc == "feature")
                $name [label=<
                    <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="2" STYLE="ROUNDED">
                    <TR><TD COLSPAN="2"><B>$name</B></TD></TR>
                        <TR>
                            <TD BGCOLOR="#555555" WIDTH="30" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> std</FONT></TD>
                            <TD BGCOLOR="#007ec6" WIDTH="41" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">feature</FONT></TD>
                        </TR>
                        <TR>
                            <TD BGCOLOR="#555555" WIDTH="30" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">alloc</FONT></TD>
                            <TD BGCOLOR="#007ec6" WIDTH="41" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">feature</FONT></TD>
                        </TR>
                    </TABLE>>]
            !elseif ($std == "no") && ($alloc == "required")
                $name [label=<
                  <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="2" STYLE="ROUNDED">
                  <TR><TD COLSPAN="2"><B>$name</B></TD></TR>
                  <TR>
                        <TD BGCOLOR="#555555" WIDTH="21" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> no_std</FONT></TD>
                        <TD BGCOLOR="#97ca00" WIDTH="10" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">yes</FONT></TD>
                    </TR>
                  <TR>
                        <TD BGCOLOR="#555555" WIDTH="31" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> alloc</FONT></TD>
                       <TD BGCOLOR="#9f9f9f" WIDTH="50" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">required</FONT></TD>
                    </TR>
                  </TABLE>>]
            !elseif ($std == "no") && ($alloc == "feature")
                $name [label=<
                  <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="2" STYLE="ROUNDED">
                  <TR><TD COLSPAN="2"><B>$name</B></TD></TR>
                  <TR>
                        <TD BGCOLOR="#555555" WIDTH="21" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> no_std</FONT></TD>
                        <TD BGCOLOR="#97ca00" WIDTH="10" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">yes</FONT></TD>
                    </TR>
                  <TR>
                        <TD BGCOLOR="#555555" WIDTH="31" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> alloc</FONT></TD>
                       <TD BGCOLOR="#007ec6" WIDTH="41" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">feature</FONT></TD>
                    </TR>
                  </TABLE>>]
            !elseif ($std == "no") && ($alloc == "no")
                $name [label=<
                  <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="2" STYLE="ROUNDED">
                  <TR><TD COLSPAN="2"><B>$name</B></TD></TR>
                  <TR>
                      <TD BGCOLOR="#555555" WIDTH="21" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> no_std</FONT></TD>
                      <TD BGCOLOR="#97ca00" WIDTH="10" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">yes</FONT></TD>
                  </TR>
                  <TR>
                        <TD BGCOLOR="#555555" WIDTH="21" ALIGN="RIGHT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12"> no_alloc</FONT></TD>
                        <TD BGCOLOR="#97ca00" WIDTH="10" ALIGN="LEFT"><FONT COLOR="#FFFFFF" FACE="sans-serif" POINT-SIZE="12">yes</FONT></TD>
                    </TR>
                  </TABLE>>]
            !endif
        !endprocedure

        $module("irox_bits", "feature", "feature")
        $module("irox_tools", "feature", "feature")
        $module("irox_cryptids", "no", "no")

        $module("irox_units", "feature", "feature")
        $module("irox_csv", "required", "required")
        $module("irox_dot", "required", "required")
        $module("irox_build_rs", "required", "required")

        $module("irox_fixedmath", "no", "no")
        $module("irox_time", "feature", "required")
        $module("irox_enums", "no", "required")
        $module("irox_carto", "feature", "required")
        $module("irox_structs", "no", "feature")
        $module("irox_types", "no", "required")
        $module("irox_compression", "no", "required")
        $module("irox_stats", "no", "required")
        $module("irox_imagery", "feature", "required")
        $module("irox_log", "feature", "required")
        $module("irox_progress", "required", "required")

}

@end