[package]
name = "irox-structs"
description = "Traits for Struct Types - linearly serialized big endian bytes"
keywords = ["irox", "reflection", "metaprogramming"]
categories = ["development-tools", "rust-patterns"]
version= "0.3.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irox-tools.workspace = true
irox-structs_derive.workspace = true
