[package]
name = "irox-structs"
description = "Traits for Struct Types - linearly serialized big/little endian bytes"
keywords = ["irox", "reflection", "metaprogramming"]
categories = ["development-tools", "rust-patterns", "no-std"]
version= "0.5.1"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irox-bits.workspace = true
irox-structs_derive.workspace = true

[features]
default = []
alloc = ["irox-bits/alloc"]

[dev-dependencies]
irox-bits = {workspace = true, features = ["alloc"]}