[package]
name = "irox-structs_derive"
description = "Derivable impls of the traits in irox-structs"
keywords = ["irox", "reflection", "metaprogramming"]
categories = ["development-tools", "rust-patterns"]
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2 = "^1"
irox-types = {version = "^0", features = ["syn"], path = "../types"}