[package]
name = "irox-enums_derive"
description = "Derivable impls of the traits in irox-enums"
keywords = ["irox", "reflection", "metaprogramming"]
categories = ["development-tools", "rust-patterns"]
version= "0.2.1"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
