[package]
name = "irox-cryptids"
description = "IROX Cryptographic Primitives - probably very hazardous"
keywords = ["irox", "crypto", "hazmat", "dragons"]
categories = ["cryptography"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[features]
_toobig-tests = [] # slow tests that take way too long to run normally.
std = ["irox-arch-x86-64"]

[dependencies]
irox-bits = {workspace = true}
irox-tools = {workspace = true}
irox-arch-x86-64 = {workspace = true, optional = true}

[dev-dependencies]
irox-tools = {workspace = true, features = ["std"]}
core_affinity.workspace = true
criterion.workspace = true
irox-arch-x86-64 = {workspace = true}
irox-stats = {workspace = true}

[lib]
bench = false

[[bench]]
name = "x25519"
harness = false
