[package]
name = "irox-stats"
description = "Various mathematical and statistics utilities"
keywords = ["irox", "mathematics", "statistics", "library", "distributions"]
categories = ["mathematics", "no-std"]
version = "0.2.9"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = []
std = []
emath = ["dep:emath"]
miniz = ["dep:miniz_oxide"]

[lints]
workspace = true

[dependencies]
irox-tools.workspace = true
irox-bits.workspace = true
irox-types.workspace = true
irox-time = { workspace = true }
irox-units = { workspace = true }
miniz_oxide = { workspace = true, optional = true }
emath = { workspace = true, optional = true }


[dev-dependencies]
irox-time.workspace = true
irox-units = { workspace = true }
irox-bits = { workspace = true, features = ["std"] }
irox-tools = { workspace = true, features = ["std"] }
irox-egui-extras = { workspace = true, features = ["plots"] }
irox-log = { workspace = true }
eframe = { workspace = true, default-features = true }
egui = { workspace = true, default-features = true }
