[package]
name = "irox-stats"
description = "Various mathematical and statistics utilities"
keywords = ["irox", "mathematics", "statistics", "library", "distributions"]
categories = ["mathematics", "no-std"]
version= "0.2.3"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
irox-tools = {path = "../tools", default-features = false, version = "0"}

[dev-dependencies]
irox-units = {workspace = true}