[package]
name = "irox-stats"
description = "Various mathematical and statistics utilities"
keywords = ["mathematics", "statistics", "library", "distributions"]
categories = ["mathematics"]
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]