[package]
name = "irox-stats"
description = "Various mathematical and statistics utilities"
keywords = ["irox", "mathematics", "statistics", "library", "distributions"]
categories = ["mathematics", "no-std"]
version= "0.2.5"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = []
std = []
miniz = ["dep:miniz_oxide"]

[lints]
workspace = true

[dependencies]
irox-tools.workspace = true
irox-bits.workspace = true
irox-types.workspace = true
miniz_oxide = {workspace = true, optional = true}


[dev-dependencies]
irox-units = {workspace = true}
irox-bits = {workspace = true, features = ["std"]}
irox-tools = {workspace = true, features = ["std"]}