[package]
name = "irox-networking"
description = "irox Networking Tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true


[dependencies]
serde.workspace = true
log.workspace = true