[package]
name = "irox-networking"
description = "irox Networking Tools"
keywords = ["irox", "networking", "extras"]
categories = ["network-programming"]
version= "0.3.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true


[dependencies]
serde.workspace = true
log.workspace = true
irox-tools.workspace = true
