[package]
name = "irox-networking"
description = "irox Networking Tools"
keywords = ["irox", "networking", "extras"]
categories = ["network-programming"]
version= "0.4.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = {workspace = true, optional = true}
log.workspace = true
irox-tools.workspace = true
irox-enums.workspace = true
irox-structs.workspace = true

[dev-dependencies]
serde_json.workspace = true
serde.workspace = true
irox-log.workspace = true
