[package]
name = "irox-carto"
description = "Cartographic & Geospatial Library"
keywords = ["coordinate", "transforms", "epsg", "projections"]
categories = ["aerospace", "data-structures", "science::geo", "mathematics"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
exclude.workspace = true

[dependencies]
irox-units = { version = "0.1", path = "../units" }
irox-enums.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[dev-dependencies]
irox-tools = {version = "0.1", path = "../tools"}