[package]
name = "irox-carto"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
irox-units = { version = "*", path = "../units" }

[dev-dependencies]
irox-tools = {version = "*", path = "../tools"}