[package]
name = "irox-carto"
description = "Cartographic & Geospatial Library"
keywords = ["irox", "coordinate", "transforms", "epsg", "projections"]
categories = ["aerospace", "data-structures", "science::geo", "mathematics"]
version= "0.2.1"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
irox-units.workspace = true
irox-tools.workspace = true
irox-enums.workspace = true
log.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
