[package]
name = "irox-tools"
description = "Stuff that should have been in the Rust STL, but aren't"
keywords = ["irox", "tools"]
categories = ["algorithms", "data-structures", "mathematics", "encoding", "network-programming"]
version= "0.5.3"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]

[dev-dependencies]
criterion.workspace = true

[features]
default = ["std"]
std = []

[lib]
bench = false

[[bench]]
name = "random"
harness = false
