[package]
name = "irox-tools"
description = "Stuff that should have been in the Rust STL, but aren't"
keywords = ["irox", "tools"]
categories = ["algorithms", "data-structures", "mathematics", "encoding", "network-programming"]
version= "0.8.3"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme = "README.md"
repository.workspace = true

[lints]
workspace = true

[dependencies]
irox-bits.workspace = true

[dev-dependencies]
criterion.workspace = true
core_affinity.workspace = true

[features]
default = []
std = ["irox-bits/std", "alloc"]
alloc = ["irox-bits/alloc"]

_toobig-tests = [] # slow tests that take way too long to run normally.

[lib]
bench = false

[[bench]]
name = "random"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
