[package]
name = "irox-app-helpers"
description = "Application Helpers Toolkit, by IROX"
keywords = ["irox"]
categories = ["command-line-interface", "config"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
irox-tools = {workspace = true, features = ["std"]}
irox-types = {workspace = true, features = ["bits"]}
