[package]
name = "irox-gpsd"
description = "Implementation of GPSd in Rust"
keywords = ["irox", "gps", "sirf", "nmea", "windows"]
categories = ["command-line-utilities", "aerospace", "science::geo", "simulation"]
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
serial = "^0.4"

human-panic = "^1.1"
env_logger.workspace = true
clap.workspace = true
time.workspace = true
clap-verbosity-flag.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
signal-hook.workspace = true
futures.workspace = true
irox-sirf.workspace = true
irox-nmea0183.workspace = true
irox-tools.workspace = true
irox-carto.workspace = true
irox-units.workspace = true
irox-networking.workspace = true

[target.'cfg(windows)'.dependencies]
irox-winlocation-api.workspace = true
