name: Rust

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on:
      - ubuntu-latest
    container:
      image: ghcr.io/spmadden/irox-dev:latest
    steps:
    - uses: spmadden/actions-checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
    - name: CI Build
      run: just run ci
  build-windows:
    runs-on:
      - windows-latest
    steps:
      - uses: spmadden/actions-checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: CI Build
        run: |
          cargo install just
          just run ci
