name: Rust

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    container:
      image: ghcr.io/spmadden/irox-dev:latest
    steps:
    - uses: actions/checkout@v4
    - name: CI Build
      run: just ci
