[package]
name = "irox-enums"
description = "Traits for better Enumerated Types"
keywords = ["irox", "reflection", "metaprogramming"]
categories = ["development-tools", "rust-patterns"]
version= "0.2.2"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
irox-enums_derive.workspace = true
