[package]
name = "cargo-describe"
description = "CLI tool to produce human-friendly information from cargo-metadata"
keywords = ["irox", "cli", "cargo", "describe"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
clap.workspace = true
log.workspace = true
git2.workspace = true
cargo.workspace = true
irox-log.workspace = true
irox-enums.workspace = true
irox-csv.workspace = true